#!/bin/bash

# Update system
sudo pacman -Syu --noconfirm

# Install packages from official repositories
sudo pacman -S --noconfirm hyprland swaybg swaylock-effects wofi code btrfs-assistant protonvpn btrfsmaintenance snapper grub-btrfs mako grim slurp wl-clipboard polkit-kde-agent pipewire-alsa pavucontrol playerctl qt5ct btop jq gvfs gvfs-mtp ffmpegthumbs python-requests pamixer brightnessctl xdg-user-dirs viewnior network-manager-applet cava thunar thunar-volman tumbler thunar-archive-plugin

# Install packages from AUR (using yay)
yay -S --noconfirm snap-pac-grub snap-pac wlogout nwg-look-bin swww waybar-hyprland-git catppuccin-gtk-theme-mocha catppuccin-cursors-mocha sddm-git sddm-catppuccin-git xdg-desktop-portal-hyprland

# Install additional fonts
sudo pacman -S --noconfirm otf-font-awesome ttf-jetbrains-mono-nerd ttf-jetbrains-mono otf-font-awesome-4 ttf-droid ttf-fantasque-sans-mono adobe-source-code-pro-fonts

# Install Thunar and xfce4
mv ~/.config/Thunar ~/.config/Thunar-back-up
cp -r config/Thunar ~/.config/

mv ~/.config/xfce4 ~/.config/xfce4-back-up
cp -r config/xfce4 ~/.config/

sudo systemctl enable --now bluetooth.service

# Set up SDDM
sudo systemctl enable sddm
sudo mkdir -p /etc/sddm.conf.d
echo -e "[Theme]\nCurrent=catppuccin" | sudo tee -a "/etc/sddm.conf.d/10-theme.conf"
sudo mkdir -p /usr/share/wayland-sessions
sudo cp misc/hyprland.desktop /usr/share/wayland-sessions/

# Disable WiFi powersave mode
echo -e "[connection]\nwifi.powersave = 2" | sudo tee -a "/etc/NetworkManager/conf.d/wifi-powersave.conf"
sudo systemctl restart NetworkManager

# Copy config files and wallpapers
for DIR in btop cava hypr foot mako swaylock waybar wlogout wofi; do
  mv ~/.config/$DIR ~/.config/$DIR-back-up
done

mkdir -p ~/.config
cp -r config/hypr ~/.config/
cp -r config/foot ~/.config/
cp -r config/wlogout ~/.config/
cp -r config/btop ~/.config/
cp -r config/cava ~/.config/
mkdir -p ~/Pictures/wallpapers
cp -r wallpapers ~/Pictures/

chmod +x ~/.config/hypr/scripts/*


echo "Installation completed!"
